package com.masdiq.util

const val userDeleted = "Successfully deleted account!"
const val userUnDeleted = "Failed to delete account!"
const val userSignOut = "Successfully sign out!"
const val tokenFailed = "Token verification failed!"
const val tokenEmpty = "Empty token id!"
const val dataAuthorized = "Data successfully authorized!"
const val dataUauthorized = "Failed to authorize data!"
const val dataSuccessCreated = "Data successfully created!"
const val dataConflict = "There is conflict in the data!"
const val dataSuccessRetrieved = "Data successfully retrieved!"
const val dataSuccessDeleted = "Data successfully deleted!"
const val dataNotFound = "Data not found!"
const val dataJsonError = "Data JSON Error"
